# Generated by Django 6.0.3 on 2026-04-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='msg',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
